version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/app.py
    command: ["python", "-u", "app/app.py"]  # -u for unbuffered output