services:
  - type: web
    name: voter-search
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11