services:
  - type: web
    name: voter-search
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data
      cp "Voter Status File 11-04 1800 CSV.csv" data/voter_status.csv
      python -m app.cli force_init
    startCommand: gunicorn app.app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --worker-class sync --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: starter
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1