services:
  - type: web
    name: voter-search
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client requests
      mkdir -p data
      python -m app.cli download
    startCommand: |
      if [ ! -f data/voters.db ]; then
        python -m app.cli download
      fi
      gunicorn app.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GDRIVE_API_KEY
        sync: false
      - key: GDRIVE_FILE_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false