services:
  - type: web
    name: voter-search
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: CSV_URL
        sync: false  # This will be set manually in Render's dashboard